<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <!-- damit kann ich zwar config im parent teilen, aber ich werde von dem parent
         abhängig und kann das repo alleine nicht mehr bauen -->
    <!--parent>
        <groupId>de.orat.math</groupId>
        <artifactId>Gazelle</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent-->
    <groupId>de.orat.math</groupId>
    <version>1.1-SNAPSHOT</version>
    <artifactId>netbeans-ocga</artifactId>
    <packaging>nbm</packaging>
    
    <build>
        <plugins>
            <!-- create folder target/nbm/modules/ext/graal/ with libs to
                 start the lsp -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.8.1</version>
                <executions>
                    <execution>
                        <id>copy-graal-runtime</id>
                        <!--phase>package</phase-->
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <!-- ${project.build.directory}/nbm/modules/ext/graal -->
                            <outputDirectory>
                                 ${project.build.directory}/graal-runtime
                            </outputDirectory>
                            <includeGroupIds>
                                org.graalvm.polyglot,
                                org.graalvm.sdk,
                                org.graalvm.truffle,
                                org.graalvm.tools,
                                org.graalvm.shadowed
                            </includeGroupIds>
                            <includeScope>runtime</includeScope>
                            <stripVersion>false</stripVersion>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy-graal-runtime-reloadable</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>
                                ${project.build.directory}/nbm/clusters/extra/modules/ext/graal
                            </outputDirectory>

                            <includeGroupIds>
                                org.graalvm.polyglot,
                                org.graalvm.sdk,
                                org.graalvm.truffle,
                                org.graalvm.tools,
                                org.graalvm.shadowed
                            </includeGroupIds>

                            <includeScope>runtime</includeScope>
                            <stripVersion>false</stripVersion>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.netbeans.utilities</groupId>
                <!-- this plugin registers the nbm packaging type -->
                <artifactId>nbm-maven-plugin</artifactId>
                <version>14.4</version>
                <extensions>true</extensions>
                <configuration>
                    <verifyRuntime>warn</verifyRuntime>
                    <!-- However, there's a wrinkle with your Snap installation: 
                         /snap/netbeans/... is read-only. NetBeans therefore cannot 
                         install the module's cluster there and should fall back to the userdir.
                         angeblich geht das mit snap installations nicht -->
                    <cluster>extra</cluster>
                    <requiresRestart>true</requiresRestart>
                    <nbmResources>
                        <nbmResource>
                            <directory>${project.build.directory}/graal-runtime</directory>
                            <targetPath>modules/ext/graal</targetPath>
                            <includes>
                                <include>**/*.jar</include>
                            </includes>
                        </nbmResource>
                    </nbmResources>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <!--version>3.8.1</version-->
                <!--version>3.13.0</version-->
                <version>3.14.1</version>
                <configuration>
                    <compilerArgument>-proc:full</compilerArgument>
                    <!--source>21</source>
                    <target>21</target-->
                    <!--compilerArgs>
                        <arg>-Xlint:unchecked</arg>
                    </compilerArgs-->
                    <compilerArgs>
                        <arg>-Xlint</arg>
                    </compilerArgs>
                </configuration>
            </plugin>
            <!-- benötigt für nbm packaging -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.4.2</version>
                <configuration>
                    <archive>
                        <manifestFile>${project.build.outputDirectory}/META-INF/MANIFEST.MF</manifestFile>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-api-annotations-common</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-api-templates</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-filesystems</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-loaders</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-nodes</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-util</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-util-lookup</artifactId>
            <version>${netbeans.version}</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-util-ui</artifactId>
            <version>${netbeans.version}</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-windows</artifactId>
            <version>${netbeans.version}</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-text</artifactId>
            <version>${netbeans.version}</version>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-core-multiview</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-awt</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-dialogs</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-modules-editor-mimelookup</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-openide-modules</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-api-lsp</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
        
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-modules-extexecution</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-modules-java-platform</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-modules-projectapi</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-api-java-classpath</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-modules-extexecution-base</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-modules-editor-document</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-modules-editor-lib2</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
                     
        <!-- hinzufügen hat nichts gebracht, -->
        <dependency>
            <groupId>de.orat.math.view</groupId>
            <artifactId>EuclidView3d</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>runtime</scope>
        </dependency>
        
        <!-- TODO brauche ich das noch-->
        <!--dependency>
            <groupId>de.orat.math.cga</groupId>
            <artifactId>ConformalGeometricAlgebra</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency-->
        <!-- indirect dependency introduced via ConformalGeometricAlgebra -->
        <!--dependency>
            <groupId>de.orat.math.ga</groupId>
            <artifactId>GeometricAlgebra</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency-->
                
        <dependency>
            <groupId>de.orat.view3d</groupId>
            <artifactId>Euclid3DViewAPI</artifactId>
            <version>1.0-SNAPSHOT</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.jogamp.java3d</groupId>
            <artifactId>vecmath</artifactId>
            <version>1.7.1</version>
            <type>jar</type>
        </dependency>
        
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.14.0</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.13.2</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.jetbrains</groupId>
            <artifactId>annotations</artifactId>
            <version>26.0.2</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-modules-textmate-lexer</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>33.5.0-jre</version>
            <type>jar</type>
        </dependency>
        
        
        <!-- lanugage server stuff -->
        
        <!-- damit kann der graalvm lsp in netbeans eingehängt werden -->
        <!--dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-modules-lsp-client</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency-->
        
        <!-- damit habe ich context class, brauche ich im den graalvm LSP starten zu können
             das macht dann aber Probleme mit transitiven Abhängigkeiten, die ich 
             ausschließen muss        -->
        <!-- ohne: java.lang.ClassNotFoundException: org.graalvm.polyglot.Context starting from ModuleCL@44980dfd[de.orat.math.netbeans.ocga] with possible defining loaders [ModuleCL@774a724e[org.netbeans.libs.graalsdk]] and declared parents [ModuleCL@7dc81a2e[org.netbeans.api.java.classpath], ModuleCL@46e451a4[org.openide.loaders], ModuleCL@7c0914d2[org.netbeans.api.templates], ModuleCL@3b55edcc[org.netbeans.modules.editor.document], ModuleCL@19cf41c[org.netbeans.modules.extexecution], ModuleCL@28b44bf[org.openide.windows], ModuleCL@6183c166[org.netbeans.libs.truffleapi], ModuleCL@4038c084[org.netbeans.api.lsp], org.netbeans.JarClassLoader@4e9e6c5, ModuleCL@3748b9cd[org.netbeans.core.multiview], ...13 more]
Caused: java.lang.NoClassDefFoundError: org/graalvm/polyglot/Context
	at de.orat.math.netbeans.ocga.GenericGraalVMLanguageServer.startServer(GenericGraalVMLanguageServer.java:79)
-->
        <!-- liefert word und nativeimage -->
        <!-- da soll auch polyglot drin sein fragezeichen -->
        <!--dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-libs-graalsdk</artifactId>
            <version>${netbeans.version}</version>
        </dependency-->
        <!-- liefert truffleapi, truffle-compiler und truffle-runtime-->
        <!--dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-libs-truffleapi</artifactId>
            <version>${netbeans.version}</version>
        </dependency-->
        
        <!--dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-libs-graaljs</artifactId>
            <version>${netbeans.version}</version>
        </dependency-->
        
        <!-- da steht truffle.MIMETypes drin ... ocgaDataObject...-->
        <!--dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-modules-debugger-jpda-truffle</artifactId>
            <version>${netbeans.version}</version>
        </dependency-->
        <!-- testweise drin, damit die truffle language auch gefunden wird -->
        <!-- das führt möglicherweise zu transitiven Abhängigkeiten von truffle classes
             in anderen versionen die ich hiermit nicht haben will. die muss ich 
             dann explizit ausschließen TODO -->
        <dependency>
            <groupId>de.dhbw.rahmlab</groupId>
            <artifactId>DSL4GA_Impl_Truffle</artifactId>
            <version>1.0-SNAPSHOT</version>
            <scope>runtime</scope> 
            <!--exclusions>
                <exclusion>
                    <groupId>org.graalvm.tools</groupId>
                    <artifactId>lsp-tool</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.graalvm.tools</groupId>
                    <artifactId>lsp_api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.graalvm.polyglot</groupId>
                    <artifactId>lsp-community</artifactId>
                </exclusion>
            </exclusions-->
        </dependency>
        <!--dependency>
            <groupId>org.graalvm.tools</groupId>
            <artifactId>lsp-tool</artifactId>
            <version>24.0.0</version>
        </dependency-->
    
    
        <!-- no dependency to my language to prevent transitive dependendies to libs
             which are shipped in a copy by netbeans itself -->    
        <!--dependency>
                <groupId>de.dhbw.rahmlab</groupId>
                <artifactId>DSL4GA_API</artifactId>
                <version>1.0-SNAPSHOT</version>
        </dependency-->
        <!--dependency>
            <groupId>de.dhbw.rahmlab</groupId>
            <artifactId>DSL4GA_Common</artifactId>
            <version>1.0-SNAPSHOT</version>
        </dependency-->

        <!-- https://mvnrepository.com/artifact/org.graalvm.tools/lsp -->

        <!-- Truffle Language Server backend API. -->
        <!--dependency>
            <groupId>org.graalvm.tools</groupId>
            <artifactId>lsp_api</artifactId>
            <version>${graalvm.version}</version>
        </dependency-->
        <!-- Core module of the polyglot Truffle Language Server backend impl -->
        <!-- brauchts damit LSPSupport baut -->
        <!-- import org.graalvm.tools.lsp.instrument.EnvironmentProvider;
             import org.graalvm.tools.lsp.server.ContextAwareExecutor;
             import org.graalvm.tools.lsp.server.LSPFileSystem;
             import org.graalvm.tools.lsp.server.TruffleAdapter;-->
        <!-- koeente aber auch das problem mit dadurch transitiver abhängigkeit zu truffle-api führen, also
             zu der Version die nicht in der IDE eingebaut ist-->
        <!--dependency>
            <groupId>org.graalvm.tools</groupId>
            <artifactId>lsp-tool</artifactId>
            <version>${graalvm.version}</version>
            <type>jar</type>
        </dependency-->

        <!-- language tooling like a sampling profiler and the chrome inspector support. -->
        <!--dependency>
             <groupId>org.graalvm.polyglot</groupId>
             <artifactId>tools-community</artifactId>
             <version>${graalvm.version}</version>
             <type>pom</type>
        </dependency-->

        <!-- fuer LSP integration NEU-->

        <!-- Polyglot API -->
        <dependency>
            <groupId>org.graalvm.polyglot</groupId>
            <artifactId>polyglot</artifactId>
            <version>${graalvm.version}</version>
        </dependency>
        <!-- Truffle -->
        <dependency>
            <groupId>org.graalvm.truffle</groupId>
            <artifactId>truffle-api</artifactId>
            <version>${graalvm.version}</version>
        </dependency>
        <!-- Generic LSP implementation -->
        <dependency>
            <groupId>org.graalvm.tools</groupId>
            <artifactId>lsp-tool</artifactId>
            <version>${graalvm.version}</version>
        </dependency>
        
        <!-- annotation to register LSP -->
        <dependency>
            <groupId>org.netbeans.api</groupId>
            <artifactId>org-netbeans-modules-lsp-client</artifactId>
            <version>${netbeans.version}</version>
            <type>jar</type>
        </dependency>
    </dependencies>
    <!-- muessen hier explizit erneut definiert werden, werden also nicht aus dem
         parent module übernommen, das parent nur aggregation macht und nicht hier
         referenziert werden kann, sonst könnte das modul nicht mehr alternativ ohne das parent
         module gebaut werden. -->
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>24</maven.compiler.release>
        <!-- netbeans 31 bundled 24.0.0 und leider nicht 24.1.1 wie in meiner sprach impl verwendet-->
        <graalvm.version>24.0.0</graalvm.version>
        <netbeans.version>RELEASE310</netbeans.version>
    </properties>
    
    <name>netbeans-ocga</name>
    <description>ocga support, also starts the language server</description>
</project>